//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiClientCore.Analyzers {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resx {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resx() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebApiClientCore.Analyzers.Resx", typeof(Resx).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 https://github.com/xljiulang/WebApiClientCore 的本地化字符串。
        /// </summary>
        internal static string helpLinkUri {
            get {
                return ResourceManager.GetString("helpLinkUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This constructor does not support attributes，Please use This constructor does not support attributes，Please use another constructor 的本地化字符串。
        /// </summary>
        internal static string WA1001_message {
            get {
                return ResourceManager.GetString("WA1001_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mismatched property constructor 的本地化字符串。
        /// </summary>
        internal static string WA1001_title {
            get {
                return ResourceManager.GetString("WA1001_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The return type must be ITask&lt;&gt; or Task&lt;&gt; or Task 的本地化字符串。
        /// </summary>
        internal static string WA1002_message {
            get {
                return ResourceManager.GetString("WA1002_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unsupported return type 的本地化字符串。
        /// </summary>
        internal static string WA1002_title {
            get {
                return ResourceManager.GetString("WA1002_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parameters do not support such modifications as ref/out 的本地化字符串。
        /// </summary>
        internal static string WA1003_message {
            get {
                return ResourceManager.GetString("WA1003_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unsupported ref / out decoration 的本地化字符串。
        /// </summary>
        internal static string WA1003_title {
            get {
                return ResourceManager.GetString("WA1003_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unsupported non-method declarations, only method declarations are allowed 的本地化字符串。
        /// </summary>
        internal static string WA1004_message {
            get {
                return ResourceManager.GetString("WA1004_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unsupported non-method declaration 的本地化字符串。
        /// </summary>
        internal static string WA1004_title {
            get {
                return ResourceManager.GetString("WA1004_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Declaring generic methods is not supported 的本地化字符串。
        /// </summary>
        internal static string WA1005_message {
            get {
                return ResourceManager.GetString("WA1005_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unsupported generic methods 的本地化字符串。
        /// </summary>
        internal static string WA1005_title {
            get {
                return ResourceManager.GetString("WA1005_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UriAttribute can only be modified on the first parameter 的本地化字符串。
        /// </summary>
        internal static string WA1006_message {
            get {
                return ResourceManager.GetString("WA1006_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unsupported decorated parameter index 的本地化字符串。
        /// </summary>
        internal static string WA1006_title {
            get {
                return ResourceManager.GetString("WA1006_title", resourceCulture);
            }
        }
    }
}
